// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObVLos7HWfv3hXr5kGKbgMFljMxcXBkE',
    appId: '1:613109271098:web:c7649161ffdd864b7b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    authDomain: 'controle-saida-aluno.firebaseapp.com',
    storageBucket: 'controle-saida-aluno.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2LqC6warQ1EwKaYfbi_O6hY7ET5uVaI',
    appId: '1:613109271098:android:4bcd9668130fe9517b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDscpdGv2UD8PhIAYGzwVm1cs5Y9qOKEFQ',
    appId: '1:613109271098:ios:cf54dcdce006c3187b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.firebasestorage.app',
    iosBundleId: 'com.example.notasAlunosWindows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDscpdGv2UD8PhIAYGzwVm1cs5Y9qOKEFQ',
    appId: '1:613109271098:ios:cf54dcdce006c3187b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    storageBucket: 'controle-saida-aluno.firebasestorage.app',
    iosBundleId: 'com.example.notasAlunosWindows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCLkjUuD7451yY7beeHkRUJy6eWQG7PtI',
    appId: '1:613109271098:web:32fa5ebe8e25424b7b4303',
    messagingSenderId: '613109271098',
    projectId: 'controle-saida-aluno',
    authDomain: 'controle-saida-aluno.firebaseapp.com',
    storageBucket: 'controle-saida-aluno.firebasestorage.app',
  );
}
